---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - janitor.homelab
  resources:
  - stalepodpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - janitor.homelab
  resources:
  - stalepodpolicies/status
  verbs:
  - get
  - patch
  - update
